# Directories to the necesary binaries

dir_stir:  "/home/jesus/simpet/include/STIR/install"
dir_simset:  "/home/jesus/simpet/include/SimSET/2.9.2"

dir_data_path: "/mnt/d/Work/SimPET/Data"
dir_results_path: "/mnt/d/Work/SimPET/Results"

# If set to one you may see some prompts to prevent you to overwrite existing data
interactive_mode: 0

# SimSET base configuration. Don't change if you don't know what you are doing
stratification: "true"
forced_detection: "true"
forced_non_absortion: "true"
acceptance_angle: 90.0
positron_range:  "true"
isotope: "f18"  # For positron range. Options are f18, c11, n13, o15, ga68, rb82, zr89
non_colinearity: "true"
minimum_energy: 350.0
weight_window_ratio: 1.0
point_source_voxels: "false"
coherent_scatter_object: "false"
coherent_scatter_detector: "false"


