# Directories to the necesary binaries
dir_stir:  "/home/jsilva/Work/simpet/include/STIR/install"
dir_simset:  "/home/jsilva/Work/simpet/include/SimSET/2.9.2"
matlab_mcr_path:  "/opt/MATLAB/MATLAB_Compiler_Runtime/v901/"
spm_path:  "/home/jesus/Work/repositories/simpet/include/spm12"
dir_data_path: "/home/jsilva/Work/simpet/Data"
dir_results_path: "/home/jsilva/Work/simpet/Results"

# If set to one you may see some prompts to prevent you to overwrite existing data
interactive_mode: 0

# Cesga Configuration
cesga: False
cesga_data_path: "/mnt/lustre/scratch/home/usc/mp/paf/SimPET/Data"
cesga_results_path:  "/mnt/lustre/scratch//home/usc/mp/paf/SimPET/Results"
cesga_max_time:  "02:00:00" # Cesga Jobs need to configure a max running time

# SimSET base configuration. Don't change if you don't know what you are doing
stratification: "true"
forced_detection: "true"
forced_non_absortion: "true"
acceptance_angle: 90.0
positron_range:  "true"
isotope: "f18"  # For positron range. Options are f18, c11, n13, o15, ga68, rb82
non_colinearity: "true"
minimum_energy: 350.0
weight_window_ratio: 1.0
point_source_voxels: "false"
coherent_scatter_object: "false"
coherent_scatter_detector: "false"


